//Contains the list of animals for the guessing game

const animaux = [
  "oryctérope",
  "alligator",
  "alpaga",
  "antilope",
  "singe",
  "tatou",
  "babouin",
  "blaireau",
  "chauve-souris",
  "ours",
  "castor",
  "bison",
  "sanglier",
  "buffle",
  "taureau",
  "chameau",
  "canari",
  "capybara",
  "chat",
  "caméléon",
  "guépard",
  "chimpanzé",
  "chinchilla",
  "tamia",
  "cougar",
  "vache",
  "coyote",
  "crocodile",
  "corbeau",
  "cerf",
  "dingo",
  "chien",
  "âne",
  "dromadaire",
  "éléphant",
  "élan",
  "brebis",
  "furet",
  "pinson",
  "poisson",
  "renard",
  "grenouille",
  "gazelle",
  "monstre de Gila",
  "girafe",
  "gnou",
  "chèvre",
  "gopher",
  "gorille",
  "grizzly",
  "marmottier",
  "cochon d'Inde",
  "hamster",
  "hérisson",
  "hippopotame",
  "porc",
  "cheval",
  "hyène",
  "bouquetin",
  "iguane",
  "impala",
  "chacal",
  "jaguar",
  "kangourou",
  "koala",
  "agneau",
  "lémurien",
  "léopard",
  "lion",
  "lézard",
  "lama",
  "lynx",
  "mandrill",
  "ouistiti",
  "vison",
  "taupe",
  "mangouste",
  "singe",
  "élan",
  "chèvre des montagnes",
  "souris",
  "mule",
  "rat musqué",
  "mustang",
  "oiseau mynah",
  "triton",
  "ocelot",
  "opossum",
  "orang-outan",
  "oryx",
  "loutre",
  "ox",
  "panda",
  "panthère",
  "perruche",
  "perroquet",
  "porc",
  "ornithorynque",
  "ours polaire",
  "porc-épic",
  "marsouin",
  "chien de prairie",
  "puma",
  "lapin",
  "raton laveur",
  "bélier",
  "rat",
  "renne",
  "reptile",
  "rhinocéros",
  "salamandre",
  "phoque",
  "mouton",
  "musaraigne",
  "renard argenté",
  "mouffette",
  "paresseux",
  "serpent",
  "écureuil",
  "tapir",
  "tigre",
  "crapaud",
  "tortue",
  "morse",
  "phacochère",
  "belette",
  "baleine",
  "chat sauvage",
  "loup",
  "carcajou",
  "wombat",
  "marmotte",
  "yak",
  "zèbre"

      //Traduit avec www.DeepL.com/Translator (version gratuite)
]

//picks a random string from the animaux array and reverse it for the guessing game
class Animaux {
  constructor() {
    this.selection = animaux[Math.floor(Math.random()*animaux.length)];
    this.reverse = reverseString(this.selection);
  }
}
